### ISSUE TITLE
How can I reset the NAN in nc files to a new Value?

### ISSUE THREAD

**Issue by Barak123748596** [Unidata/netcdf4-python#1007]
My code is like the following:

```python
from netCDF4 import Dataset

PATH = 'run.nc'
data = Dataset(PATH)
cloud = data['cloud'][:, :, :]  # shape=(month, lat, lon)
temp = cloud[0, -1:, 0]
print(temp)
```

and the output is like the following:
```
D:\Miniconda3\python.exe D:/try.py
--

Process finished with exit code 0
```

The code means that the cloud coverage of the north pole is not a number. Now I want to set all places where is not a number to zero. What can I do to achieve this goal?

My wishing code is like this:
`cloud[cloud=np.nan] = 0`

However, when I try the code 
`print(cloud[0,-1,0]==np.nan)`
it still outputs:
```
D:\Miniconda3\python.exe D:/try.py
--

Process finished with exit code 0
```

What does it mean? Thank you very much!

**Comment by jswhit2** [comment]
The '--' means that the data is [masked](https://docs.scipy.org/doc/numpy/reference/maskedarray.html)  there either because
1) the value is equal to the `missing_value` attribute, or outside the `valid_range`.
2) no data was every written there (so the data is equal to the `_FillValue`

You can get the actual data by invoking  `Dataset.set_auto_mask(False) ` before you read the data.  Instead of returning a masked array, the interface will then just give you the raw data values.

**Comment by Barak123748596** [comment]
It works, and its return value is `9.96920997e+36`. Thank you very much!
