### ISSUE TITLE
Float variable in NetCDF 1.5 is read as an Integer

### ISSUE THREAD

**Issue by EnlNovius** [Unidata/netcdf4-python#1077]
I have a file containing a rainfall variable (3D) that corresponds to an array of floats (see the attached file):

[problem_float.zip](https://github.com/Unidata/netcdf4-python/files/5904590/problem_float.zip)

(I had to zip the file, github does not accept NetCDF files).

If I read this file with an old version of NetCDF4 (for example: python 3.7.4 and netCDF4 1.4.2 or python 3.5.3 and netCDF4 1.2.4) the variable is correctly read as a float :

```
>>> import netCDF4 as nc
>>> f = nc.Dataset('problem_netcdf_float.nc', 'r')
>>> print(f.variables['rainfall'][:])

[[[ 1.9980621   0.76921797  0.49901453  0.81992507  0.588546     1.3286734 ]
  [ 1.4248223   0.3942658    0.42665148  0.5156806    0.55485564 1.0885825 ]
  [ 2.6024692   0.17779078  0.32485983  0.72635233  0.9185372   1.673451 ]
  [10.9001255  10.232512    5.8083973    3.1431255    2.7410784   2.166116 ]
  [13.193829    16.326796    12.032895    4.3488574    1.7199461   1.6601689 ]]]
```

Howether, if I read this variable with netcdf 1.5.2 or 1.5.4, the variable is read as an integer :

```
>>> import netCDF4 as nc
>>> f = nc.Dataset('problem_netcdf_float.nc', 'r')
>>> print(f.variables['rainfall'][:])

[[[ 1  0  0  0  0  1]
  [ 1  0  0  0  0  1]
  [ 2  0  0  0  0  1]
  [10 10  5  3  2  2]
  [13 16 12  4  1  1]]]
```

**Comment by akrherz** [comment]
My guess is that the issue is the `scale_factor` and `add_offset` values are integers

```
		rainfall:scale_factor = 1 ;
		rainfall:add_offset = 0 ;
```

If I change those to floats, current `netCDF4` creates a `float32` dtype array.

**Comment by jswhit** [comment]
yes, that is the problem.  You can disable the auto-scaling with Dataset.set_auto_scale(False).

**Comment by EnlNovius** [comment]
Dataset.set_auto_scale(False) worked perfectly, thank you both for your help !

```
>>> import netCDF4 as nc
>>> f = nc.Dataset('problem_netcdf_float.nc', 'r')
>>> f.variables['rainfall'].set_auto_scale(False)
>>> print(f.variables['rainfall'][:])

[[[ 1.9980621   0.76921797  0.49901453  0.81992507  0.588546     1.3286734 ]
  [ 1.4248223   0.3942658    0.42665148  0.5156806    0.55485564 1.0885825 ]
  [ 2.6024692   0.17779078  0.32485983  0.72635233  0.9185372   1.673451 ]
  [10.9001255  10.232512    5.8083973    3.1431255    2.7410784   2.166116 ]
  [13.193829    16.326796    12.032895    4.3488574    1.7199461   1.6601689 ]]]
```

**Comment by radosuav** [comment]
I also run into this issue:

```
IPdb [30]: t2m = fid.variables["t2m"]

IPdb [31]: t2m
<class 'netCDF4._netCDF4.Variable'>
float32 t2m(time, latitude, longitude)
    _FillValue: nan
    units: K
    long_name: 2 metre temperature
    add_offset: 0
    scale_factor: 1
unlimited dimensions: 
current shape = (7848, 12, 15)
filling on

IPdb [32]: t2m[:]
masked_array(
  data=[[[283, 283, 283, ..., 281, 281, 282],
         [283, 283, 282, ..., 281, 282, 282],
         [283, 282, 282, ..., 282, 282, 282],
```
And the suggested workaround also worked:
```
IPdb [33]: t2m.set_auto_maskandscale(False)

IPdb [34]: t2m[:]
array([[[283.94275, 283.64932, 283.21524, ..., 281.76178, 281.87772,
         282.07446],
        [283.68643, 283.20975, 282.7358 , ..., 281.90244, 282.02432,
         282.20068],
        [283.21317, 282.72046, 282.34937, ..., 282.0197 , 282.13037,
         282.30194],
```

However, I think that this behaviour is quite dangerous, because the conversion is unexpected, silent and leads to loss of precision. This can result in very tricky bugs. ALso, in xarray the data is read as float both with and without auto scaling. It seems that this behavior is an unintended consequence of fix to https://github.com/Unidata/netcdf4-python/issues/913, which tried to address the opposite issue (lack of expected conversion from short to float).

**Comment by davidhassell** [comment]
Hi, it is the case that the `add_offset` and `scale_factor` attribute are expected to be of the same type as the unpacked data, so I'm inclined to think that netCDF4-python is doing the right thing, here, since these attributes are integers in this example (https://www.unidata.ucar.edu/software/netcdf/documentation/4.7.4-pre/attribute_conventions.html).

I don't know if your using them, but this is also reiterated, in a slightly tighter fashion, by the CF conventions (https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#packed-data).

Thanks, David

**Comment by radosuav** [comment]
Thanks, I wasn't aware that this behavior is part of NetCDF convention. But it's still a bit tricky ;)
