### ISSUE TITLE
How does netCDF4 broadcast numpy arrays?

### ISSUE THREAD

**Issue by headtr1ck** [Unidata/netcdf4-python#1083]
How exactly does automatic broadcasting numpy arrays work with netCDF4?
I cannot assign a netCDF-variable some values where some dimension of the numpy array has length 1, which is possible in numpy. See below some example.
I get the error message: "IndexError: size of data array does not conform to slice".

* the version of the software with which you are encountering an issue
  * netCDF4==1.5.5
  * numpy==1.20.0
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.)
  * python==3.9.1
  * linux
* a description of the issue with the steps needed to reproduce it
```
import netCDF4
import numpy as np

with netCDF4.Dataset("test.nc", "w") as nc:
    nc.createDimension("test", 5)
    v = nc.createVariable("var", "f8", ("test", "test"))

    v[:] = 1 # works
    v[:] = np.ones(()) # works
    v[:] = np.ones((1,)) # works
    v[:] = np.ones((5,)) # works
    v[:] = np.ones((5,5)) # works
    v[:] = np.ones((5,1)) # fails
```

**Comment by jswhit** [comment]
Can't give you a quick answer since it's been a while since I've looked at the [code](https://github.com/Unidata/netcdf4-python/blob/7a886dba4fe484a021938376275c6567b946b70c/src/netCDF4/utils.py#L89).  

You should not expect it to behave the same as numpy.  It certainly could be made more consistent.  Ideally, we would leverage the numpy code to do the indexing and broadcasting, but I have not been able to figure out how to do that.

**Comment by jswhit** [comment]
potential solution in PR #1084

**Comment by jswhit** [comment]
PR #1084 merged, thanks for the bug report (happily it turned out to be an easy fix)
