### ISSUE TITLE
parallel=True requires both pnetcdf and MPI-enabled HDF5 regardless of format

### ISSUE THREAD

**Issue by sjsmith757** [Unidata/netcdf4-python#1123]
Hi! I have noticed while trying to use netcdf4 in parallel mode for a parallel enabled netcdf-c library, the code requires MPI-enabled netcdf-c functioning for all netCDF formats, i.e. both pnetcdf and parallel netcdf4 built on MPI-enabled HDF5 (c.f. "and" operator at line 2141 in _netcdf4.pyx). However the code logic in the following lines and elsewhere suggests that the MPI-enabled dependencies required should depend on the output format (NetCDF3 v NETCDF4). The documentation also suggests only one of these dependencies should be required: "Parallel IO further depends on the existence of MPI-enabled HDF5 or the PnetCDF library." (taken from https://unidata.github.io/netcdf4-python/). It seems to me that the code should enforce only the dependencies required for the requested format. Alternatively, it would seem that the documentation should make clear both are required regardless of format. I think it would be a small change either way, but it would be helpful to know at the outset what is required!

Description:
Trying to run examples/mpi_example.py results in ValueError 'parallel mode requires MPI enabled netcdf-c', even though nc-config --has-parallel4 returns yes (but --has-pnetcdf returns no).

I am using:

netcdf4-python=1.5.7
mpi4py=3.0.3
numpy=1.19.5
cython=0.29.23
cftime=1.5.0
setuptools=47.1.0
hdf5=1.12
netcdf-c=4.7.4
gcc=9.3.0
mvapich=2.3.5
python=3.8.5
Red Hat Enterprise v8

**Comment by jswhit** [comment]
You must be referring to this check

```python
            IF HAS_PARALLEL4_SUPPORT != 1 and HAS_PNETCDF_SUPPORT != 1:
                msg='parallel mode requires MPI enabled netcdf-c'
                raise ValueError(msg)
```

which only raises the ValueError if neither pnetcdf or parallel4 is available.  This suggests to me that the failure you see is due to setup.py not detecting parallel4 support correctly.  The check involves looking for `#define NC_HAS_PARALLEL4` in  netcdf_meta.h.

**Comment by jswhit** [comment]
@sjsmith757 I am going to close this since the title does not really indicate the true nature of the problem. Please re-open with a new title if you believe that setup.py is not correctly detecting parallel4 support in the netcdf library. You can check this by seeing if the included nc_meta.h file indeed does have #define NC_HAS_PARALLEL4.
