### ISSUE TITLE
Process getting killed when attempting to open zarr directory

### ISSUE THREAD

**Issue by cryptoboxcomics** [Unidata/netcdf4-python#1177]
Hello. I was attempting to open a zarr directory using the following code snippet in python3:

```
from netCDF4 import Dataset
nc = Dataset("file:///Users/UserName/Downloads/zarr_no_compression/#mode=nczarr,zarr","r")
```
It would freeze for a few minutes, and then it would eventually return the following error:
```
zsh: killed     python3 netcdf_test.py
```

Version of netCDF4: 1.6.0
OS: Mac OSX, but I have also tried this on other distributions such as Debian 5 and Centos 7.

Is this notation for opening zarr directories not supported?

Sample tar file attached.
[zarr_no_compression.tar.gz](https://github.com/Unidata/netcdf4-python/files/9143448/zarr_no_compression.tar.gz)

**Comment by jswhit** [comment]
I can reproduce this, but I'm pretty sure this is a netcdf-c question- the URL is just passed on to the c lib.  @DennisHeimbigner are zarr directories supported?

**Comment by DennisHeimbigner** [comment]
First, the url is incorrect. It should be this (assuming you are using netcdf-c-4.9.0).
> file:///Users/UserName/Downloads/zarr_no_compression/#mode=zarr,file

Currently the netcdf-c zarr code is not very good at auto-detecting the kind of
storage format being used. So, you need to tell it, which is why the ",file" part of
the URL. There are several other formats such as "zip".

Anyway, I tested it on netcdf-c-4.9.0 using ncdump and it seems to read ok.
The file support was put in early on, so if you are using, say, 4.8.x, the above
url should work.

**Comment by cryptoboxcomics** [comment]
Ah! I see! I didn't know I needed the ,file at the end. I got the code to work with #mode=nczarr,file and #mode=zarr,file with this.

The reason why this notation appeared correct was that I was looking at the issue here: https://github.com/Unidata/netcdf-c/issues/2449 , and it seemed like ncdump was able to return values with this URL.

**Comment by DennisHeimbigner** [comment]
missed that.
Anyway, the definitive text on nczarr is in the document netcdf-c/docs/nczarr.md.
