### ISSUE TITLE
windows tests failing on master

### ISSUE THREAD

**Issue by jswhit** [Unidata/netcdf4-python#1186]
cython compilation fails to find zlib

creating D:\a\netcdf4-python\netcdf4-python\build\lib.win-amd64-cpython-38
creating D:\a\netcdf4-python\netcdf4-python\build\lib.win-amd64-cpython-38\netCDF4
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\HostX86\x64\link.exe" /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Miniconda\envs\TEST\Library\lib /LIBPATH:C:\Miniconda\envs\TEST\Library\lib /LIBPATH:C:\Miniconda\envs\TEST\libs /LIBPATH:C:\Miniconda\envs\TEST /LIBPATH:C:\Miniconda\envs\TEST\PCbuild\amd64 "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\ATLMFC\lib\x64" "/LIBPATH:C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64" hdf5_hl.lib hdf5.lib netcdf.lib zlib.lib /EXPORT:PyInit__netCDF4 build\temp.win-amd64-cpython-38\Release\src\netCDF4\_netCDF4.obj /OUT:build\lib.win-amd64-cpython-38\netCDF4\_netCDF4.cp38-win_amd64.pyd /IMPLIB:build\temp.win-amd64-cpython-38\Release\src\netCDF4\_netCDF4.cp38-win_amd64.lib
LINK : fatal error LNK1181: cannot open input file 'zlib.lib'
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.33.31629\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
[end of output]

**Comment by jswhit** [comment]
github actions workflow here: https://github.com/Unidata/netcdf4-python/blob/master/.github/workflows/miniconda.yml

**Comment by jswhit** [comment]
@ocefpaf do you have any thoughts on how to fix this?

**Comment by ocefpaf** [comment]
I suspect that a recent change in the zlib in conda-forge may be the cause. Investigating...

**Comment by hmaarrfk** [comment]
ok I think i got to the bottom of it:

Generally speaking, this package should add a direct dependency on `zlib`. You are linking to it:
https://github.com/Unidata/netcdf4-python/blob/065ba176004bb13c2124dc49e8f8366a31297ecc/setup.py#L476

What happened recently, is that I cleaned up the run export to avoid shipping everybody static versions of zlib at run time. In that cleanup, we also removed build files from the `libzlib` package. 

This caused alot of packages that implicitely dependeded on zlib to fail.

As such, to fix this build process, my thought, is that you should directly depend on zlib, instead of implicitely depending on it.

On linux and mac, there is likely something that is automatically pulling in `zlib` and not just `libzlib`.

**Comment by ocefpaf** [comment]
I'll test this in #1187 now. Thanks @hmaarrfk!
