### ISSUE TITLE
netCDF4 fails to install via pip

### ISSUE THREAD

**Issue by mckinley-brumback** [Unidata/netcdf4-python#1344]
I am trying to install netCDF4 (most recent version, netcdf4-1.7.1) in a Conda environment with Python 3.11 via pip. I am using an M2 Max Apple Silicon computer with OS 13.4.1. When I run 
$ pip install netcdf4
fails to install because of missing path variable for HDF5_DIR. The full error text is copied below. 

I tried installing HDF5 via conda
$ conda install h5py
Which installed without issue. But I get the same error message when trying to pip install netCDF. Any help is much appreciated!

Error output:
`(stingray062024) ~:pip install netcdf4 
Collecting netcdf4
  Using cached netcdf4-1.7.1.post1.tar.gz (827 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      reading from setup.cfg...
          HDF5_DIR environment variable not set, checking some standard locations ..
      checking /Users/mbrumback/anaconda3/envs/stingray062024/include...
      HDF5 library version: 1.14.3 headers found in /Users/mbrumback/anaconda3/envs/stingray062024/include
      HDF5 library version: 1.14.3 found in /Users/mbrumback/anaconda3/envs/stingray062024
      NETCDF4_DIR environment variable not set, checking standard locations..
      checking /Users/mbrumback/anaconda3/envs/stingray062024...
      checking /Users/mbrumback/anaconda3/envs/stingray062024/Library...
      checking /Users/mbrumback...
      checking /usr/local...
      checking /sw...
      checking /opt...
      checking /opt/local...
      checking /opt/homebrew...
      checking /usr...
      Traceback (most recent call last):
        File "/Users/mbrumback/anaconda3/envs/stingray062024/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/mbrumback/anaconda3/envs/stingray062024/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/mbrumback/anaconda3/envs/stingray062024/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/pqd3bzqx6l9c7gz7y3l271sc0000gn/T/pip-build-env-hu4y1_pm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/fk/pqd3bzqx6l9c7gz7y3l271sc0000gn/T/pip-build-env-hu4y1_pm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/fk/pqd3bzqx6l9c7gz7y3l271sc0000gn/T/pip-build-env-hu4y1_pm/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 292, in <module>
      ValueError: did not find netCDF version 4 headers
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by ocefpaf** [comment]
> I tried installing HDF5 via conda
> $ conda install h5py

The h5py package is not hdf5. It is a python package that uses hdf5 under the hood but is not suitable to build other packages that require a full hdf5 installation. Also, you need to set the HDF5_DIR for your hdf5 installation. With that said, if you are using conda why not install a pre-built netcdf4 from conda-forge?

```
conda install netcdf4 --channel conda-forge
```

I also don't understand why pip is trying to install it from source instead of downloading the wheel (binary distribution). I wonder if the wheels are not compatible with your system. They are compiled for macosx_14/arm64.

**Comment by mckinley-brumback** [comment]
I did not realize I could install from conda-forge, I must have missed that in the documentation. The conda-forge install did work without issue, thank you!

**Comment by ocefpaf** [comment]
Closing this. Please reopen if you disagree.

PS: You should find all the packages you need in the conda-forge and mixing conda packages with pip is not advised. However, if you do require packages via pip from PyPI, I'm still curious why that tried to build from source instead of installing the wheel. Something is happening there but I don't own a mac to test it.

**Comment by cchwala** [comment]
@ocefpaf FYI, I had a similar problem with the pip install of netCDF4 and I think I have an answer for this question that you asked above:

>  I'm still curious why that tried to build from source instead of installing the wheel. Something is happening there but I don't own a mac to test it.

For MacOS there are currently two wheels for each Python version. One for MacOS 12.0+ and one for MacOS 14.0+. I had an older version and because of this pip tried to do a source install.

I fixed it by downloading the recent wheel and just renaming it so that it matches my MacOS version. Seems like pip only checks the filename to see which OS version a wheel is supposed to support. I have, however, not checked functionality in detail, because this was just a test for a pip install. Normally I use conda-forge.

**Comment by ocefpaf** [comment]
> I fixed it by downloading the recent wheel and just renaming it so that it matches my MacOS version. Seems like pip only checks the filename to see which OS version a wheel is supposed to support. I have, however, not checked functionality in detail, because this was just a test for a pip install. Normally I use conda-forge.

Indeed we had to drop some older macOSes due to the complications to build them. I am working on something that would use conda-forge dependencies and would increase the OSes coverage, but that won't be ready soon.

**Comment by cchwala** [comment]
Thanks for the info and, in particular, for the work you put into this!

Good to hear that old MacOS versions, like mine, will be support in the future. But at some point people like me just need to update... 😇.

Installing the scientific Python packages via pip has improved already so much during the last years. Keep up the good work!
