### ISSUE TITLE
New post release to create Python 3.13 wheels

### ISSUE THREAD

**Issue by ocefpaf** [Unidata/netcdf4-python#1370]
The CIs are passing for Python 3.13, the wheels are getting created and tested in the latest commit. We should be OK to mint a post release of 1.7.1 to upload those wheels.

**Comment by jswhit** [comment]
OK thanks @ocefpaf. I will create a new release this week.

**Comment by neutrinoceros** [comment]
Is it expected that windows + cp313 wheels are missing ?

**Comment by veenstrajelmer** [comment]
Thanks for creating this release! One minor administrative issue, python 3.13 was not added to the classifiers yet:
https://github.com/Unidata/netcdf4-python/blob/7ee6af5e7a72630ffdd2080625ef76e4ae8dbe5d/pyproject.toml#L23-L29

**Comment by veenstrajelmer** [comment]
@jswhit and @ocefpaf can this issue be reopened or should the wheels already be available?

**Comment by neutrinoceros** [comment]
There now is a wheel for cp313 + windows (amd64):

https://files.pythonhosted.org/packages/66/b5/e04550fd53de57001dbd5a87242da7ff784c80790adc48897977b6ccf891/netCDF4-1.7.2-cp313-cp313-win_amd64.whl#sha256=5c5fbee6134ee1246c397e1508e5297d825aa19221fdf3fa8dc9727ad824d7a5

**Comment by veenstrajelmer** [comment]
@neutrinoceros thanks a lot for mentioning this. Indeed all works now. I did not test it after it failed right after the release, but see now that the py3.13 windows wheels were already made available 1 day after the release of netcdf 1.7.2.

@jswhit and @ocefpaf I also noticed there are no python 3.8 wheels available for windows for netcdf 1.7.2. Could these still be added? I am aware that python 3.8 has been dropped, but since the package says it supports python 3.8, I would have expected these wheels to be present there.

One additional request, could you also add the release to github? https://github.com/Unidata/netcdf4-python/releases
