### ISSUE TITLE
Compression: I need your help

### ISSUE THREAD

**Issue by micromad** [Unidata/netcdf4-python#258]
Hi,

I'm using netCDF4 python on two different computers: my laptop and my desktop at work. I've compiled netCDF with the same script on the both computers (same HDF5 lib version (1.8.12), same netcd4 (4.3.1.1), same python-netCDF4 version (1.0.8) same options,...), the only difference is the version of linux which is newer on my laptop (Fedora 18).

When I use the nc3tonc4 script on my desktop, the size of one of my file decrease from 722MB to 158MB.

When I use the same script on my laptop, the compression is much more efficient, from 722 MB to 6.3MB. (I just precise that the file is filled with almost the same value.)

I don't understand where the difference comes from ? I've tried different version of libz but nothing change. Can you help me ? Getting an huge compression will be helpfull because I need periodically to upload them.

You can download the 6.6MB file here:
https://cloud.lsce.ipsl.fr/public.php?service=files&t=2fd610631cebb35d4b4fe45f0ba9145b

Thanks in advance !!!

**Comment by mdecker** [comment]
I have just tried to convert the file using the latest netCDF4-python and numpy 1.9.1. The result is this:
/usr/local/lib/python2.7/dist-packages/numpy/lib/arraysetops.py:366: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  mask |= (ar1 == a)
Traceback (most recent call last):
  File "/usr/local/bin/nc3tonc4", line 5, in <module>
    pkg_resources.run_script('netCDF4==1.1.3', 'nc3tonc4')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources.py", line 1401, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/netCDF4-1.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/nc3tonc4", line 280, in <module>

  File "/usr/local/lib/python2.7/dist-packages/netCDF4-1.1.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/nc3tonc4", line 118, in nc3tonc4

  File "netCDF4.pyx", line 3392, in netCDF4.Variable.__setitem__ (netCDF4.c:38878)
  File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 3491, in filled
    fill_value = _check_fill_value(fill_value, self.dtype)
  File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 421, in _check_fill_value
    raise TypeError(err_msg % ndtype)
TypeError: Cannot set fill value of string with array of dtype float32

The file itself does indeed seem to pose the problem: A string-valued "NaN" does not go well with a float variable. You might have found some "lucky" combination of numpy and netcdf that actually did something without complaining because of some (wrong) automatic conversion. The resulting compressed file is most likely useless because most data is missing from it. If you want to use NaNs in your files at all, then you should use the proper data type for the fill value. 
Even then using NaNs in netCDF is tricky business as there is no explicit support within the library. See this post for reference: http://www.unidata.ucar.edu/mailing_lists/archives/netcdfgroup/2002/msg00104.html

When I compressed/converted my data to netCDF4 I also wrote a script that made sure that the file contents were absolutely identical.

I vote for closing this issue as it is a dataset specific problem that seems to be prevented by better type checking in recent versions of numpy/netCDF4-python.
