### ISSUE TITLE
ValueError: filepath method requires netcdf lib >= 4.1.2, you have 4.2.1.1

### ISSUE THREAD

**Issue by martinjuckes** [Unidata/netcdf4-python#263]
I have just installed netCDF4 with the version 4.2.1.1 netcdf library. Running these two lines:
nc = netCDF4.Dataset( 'x.nc', 'w' )
nc.filepath()
results in the error message "ValueError: filepath method requires netcdf lib >= 4.1.2, you have 4.2.1.1".
It looks to me as though the netcdf library version is not being interpreted correctly.

**Comment by mdecker** [comment]
I just ran into the same problem. "just stop using pip" does not seem like an adequate solution to this problem in my opinion. This should build properly no matter if compiled manually or by easy_install/pip.
I might still spend some time looking into this...

**Comment by mdecker** [comment]
OK, it turns out that it is the build script's fault somehow:
Simply running `python setup.py install` does not regenerate the `netCDF4.c` file. So it actually does not matter if your local netCDF lib supports filepath - the option will simply never be set. This is likely the problem that `pip` and `easy_install` run into.
An updated `netCDF4.c` file is only generated when using `python setup.py build`. I can confirm that the resulting module supports `filepath()`.
I would naïvely expect that `build && install` and simply running `install` lead to the same result - which is obviously not the case here. Maybe someone with more insights into the build script is able to fix this in a timely manner? I don't see any reason why the two approaches should generate different results.

**Comment by dopplershift** [comment]
Good catch. I'll re-open for now to try to encourage some more eyes. I'd rather let someone more versed with the build script to decide, however.

**Comment by mdecker** [comment]
I'm sorry to bump this again. But is there any chance of fixing this problem soon? I still fail to see any good reason for this build behaviour. And nobody else commented on it within the last two weeks either.

Should this change really break something it will most certainly be easy to roll it back - we're talking about one line in a setup script here after all. On the other hand the current install process breaks features for me and likely other people who still have not figured out what is actually wrong.

**Comment by jswhit** [comment]
I honestly can't remember why I did it this way.  I don't see the harm in changing it (pull request #338).

**Comment by mdecker** [comment]
As far as I am concerned this problem is solved. So this issue could hopefully be closed for good this time.
