### ISSUE TITLE
Deep copy on netCDF4.netcdftime.datetime

### ISSUE THREAD

**Issue by davidhassell** [Unidata/netcdf4-python#415]
Hello,

```copy.deepcopy``` does not seem to work on netCDF4 datetime objects. Is this deliberate, or can we fix it?

```
In [5]: import netCDF4
In [6]: netCDF4.__version__
Out[6]: '1.1.7'
In [7]: t = netCDF4.netcdftime.datetime(2001, 12, 1)
In [8]: t
Out[8]: 2001-12-01 00:00:00
In [9]: import copy
In [10]: copy.deepcopy(t)
Out[10]:    0-01-01 00:00:00
```
All the best,

David

**Comment by shoyer** [comment]
This is not deliberate. The fact that this no longer works is likely a side effect of a recent change that moved `netcdftime.datetime` to a Cython extension class (for speed).

We can fix this by defining `__copy__` and `__deepcopy__` methods:
https://docs.python.org/2/library/copy.html

Note that generally there is no need to copy `netcdftime.datetime` objects, because they are immutable. Of course this can still come up in the process of a recursive deepcopy. 

Any interest in putting together a PR?

**Comment by davidhassell** [comment]
Hi,

That's good to hear. I thought I'd ask before a doing a pull request in case I'd missed something. I'll submit one soon.

My use case is like you suggest - wanting to deep copy a numpy array of objects, some of which might not be datetime objects.

All the best,

David

**Comment by jswhit** [comment]
Turns out adding a __reduce__ method to netcdftime.datetime fixes this (pull request #415).

**Comment by jswhit** [comment]
merging now and closing, @davidhassell please re-open if you have any problems with it...

**Comment by shoyer** [comment]
thanks @jswhit !
