### ISSUE TITLE
`cdfid` error intermittently on reading or writing datasets

### ISSUE THREAD

**Issue by om-henners** [Unidata/netcdf4-python#417]
Hi,

On intermittent netCDF4 files that we are working on on our cluster we're getting the following error, either when we're trying to read the file (the most common), or when we're trying to write a new file.

    netcdf: 65536 is not a valid cdfid

The files we are trying to read were previously created in another Python session on the same machine, and transferring the files back to the desktop to access them gives no issues - the files open without a problem.

The error itself appears to be being thrown by the C library in the background, as the error is killing the entire Python session and not being caught by the exception handler.

If there is anything you can recommend or help with it would be much appreciated. And if you'd like any further information please let me know.

Cheers,
Henry

**Comment by jswhit** [comment]
That error is actually coming from the HDF4 library (libmfhdf), not the netcdf library.  Are these hdf files?

I found this ticket:

http://www.unidata.ucar.edu/support/help/MailArchives/netcdf/msg09788.html

which suggests that problem arises when libmfdf and libnetcdf are both linked as shared libs, and the wrong symbol (the one from mfdf instead of netcdf) is begin picked up.  The suggested solution is to recompile libmfdf with -DHAVE_NETCDF.

**Comment by om-henners** [comment]
Thanks. I'll try re-compiling HDF4 as the post suggets and let you know how I go.

The files we are working with are NetCDF4 files (so HDF5 in the background)
