### ISSUE TITLE
Set chunk size

### ISSUE THREAD

**Issue by cythomli** [Unidata/netcdf4-python#561]
I have a variable with dimension (time, lat, lon) = (2922, 49, 96). How should I set the chunk size to use less memory?

**Comment by jswhit** [comment]
difficult to say without more information.  Does the variable have an unlimited dimension?  How do you anticipate accessing the data?

Some good information here: http://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_why_it_matters.

Most of it has to do with how chunking affects read/write speeds, not memory usage though.  Can you explain what issues you are seeing with memory usage?

**Comment by lisapalathingal** [comment]
The variable has 3 dimensions: time, latitude, and longitude. I read the values from the file and append those values to a list. The list is stored as the variable data. Appending all the values to the list makes the program run getting killed. Any ideas to resolve the issue?

**Comment by jswhit** [comment]
I think we need to see actual code...

**Comment by lisapalathingal** [comment]
[animationToNetcdf.py.zip](https://github.com/Unidata/netcdf4-python/files/232556/animationToNetcdf.py.zip)

**Comment by lisapalathingal** [comment]
Here's the code

**Comment by jswhit** [comment]
can't run your program, since I don't have gdal.  From your description is sounds like you're running out of memory when appending numpy arrays to a list.  If that's true, it has nothing to do with chunksizes, or netcdf4-python.  Perhaps you could try writing data to the netcdf variable one time slice at a time, instead of appending everything to a list and then writing the result?

**Comment by shoyer** [comment]
If you're running out of memory loading data from netcdf files, I would give dask.array and/or xarray a try:
http://xarray.pydata.org/en/stable/dask.html

**Comment by lisapalathingal** [comment]
Thanks! Will try that.
