### ISSUE TITLE
Check valid_min, valid_max and valid_range when masking

### ISSUE THREAD

**Issue by duncanwp** [Unidata/netcdf4-python#576]
It would be great if the masking would respect valid_min, max and range when loading variables - to be honest I was a little surprised it doesn't already. 

This is fairly easy to do manually, but because it has to come before the scaling it means I have to do the masking _and_ scaling myself which is a bit of a pain.

**Comment by jswhit** [comment]
At 

http://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html

I see

"Generic applications should treat values outside the valid range as missing"  

Are you suggesting that if a value is outside the valid range, it should be masked (i.e. treated the same way as a missing value)?    I wonder what other applications do.

**Comment by duncanwp** [comment]
Precisely. Those conventions also define valid_min and valid_max as well.

I've implemented this recently in https://github.com/cedadev/cis due to user feedback, here: https://github.com/cedadev/cis/blob/master/cis/data_io/netcdf.py#L252, but I'm sure there are more elegant solutions. Particularly - the conventions state that "valid_range must not be defined if either valid_min or valid_max is defined", but I don't enforce that. I also only warn if I can't parse the metadata as I don't consider it a show-stopper, but you might want to be stricter.

**Comment by jswhit** [comment]
created a branch (valid_minmax) to work on this.

**Comment by jswhit** [comment]
implemented this part:

"If neither valid_min, valid_max nor valid_range is defined then generic applications should define a valid range as follows. If the data type is byte and _FillValue is not explicitly defined, then the valid range should include all possible values. Otherwise, the valid range should exclude the _FillValue (whether defined explicitly or by default) as follows. If the _FillValue is positive then it defines a valid maximum, otherwise it defines a valid minimum. "

**Comment by jswhit** [comment]
@duncanwp, will wait for your input before merging.

**Comment by duncanwp** [comment]
Wow, that was quick, thanks! I've made a few comments inline.

**Comment by jswhit** [comment]
The pull request was merged, closing now...

**Comment by duncanwp** [comment]
Great, thanks @jswhit
