### ISSUE TITLE
wrong time zone conversion?

### ISSUE THREAD

**Issue by pgamez** [Unidata/netcdf4-python#685]
This is from the doc of num2date:

> The returned datetime objects represent UTC with no time-zone offset, even if the specified units contain a time-zone offset.

The local hour "2000-01-01 00:00" in the timezone UTC+01 corresponds with the hour "1999-12-31 23:00" in UTC coordinates, so we have to substract the time offset to convert from local hour to UTC.

But num2date seems to compute the opposite:

```python
import netCDF4 as nc

units = 'hours since 2000-01-01 00:00 +01:00'
tstep_local = 0
time_utc = nc.num2date(tstep_local, units)
print(time_utc)
```

The result of the code above **adds** the offset instead of subtracting

`2000-01-01 01:00:00`

Maybe the conversion in num2date and date2num are swapped...

Thanks

Pedro

**Comment by jswhit** [comment]
However, it does produce the correct answer (I think) here

    import netCDF4 as nc
    from datetime import datetime
    units = 'hours since 2000-01-01 00:00 +01:00'
    d = datetime(2000,01,01)
    print nc.date2num(d,units=units)

The result is
   
   -1.0

which I believe is correct, since UTC is 1 hour behind `units`.

**Comment by pgamez** [comment]
Thank you Jeff,

ummm... The doc of date2num says that "The datetime objects must be in UTC with no time-zone offset"

I assume that the values of the netcdf's time variable should be in local time (consistently with their units), so...

If d is in UTC and it is 1 hour behind local ==> local hour is datetime(2000,01,01, 1) ==> result = +1.0 (one hour after the reference time)

Pedro

**Comment by jswhit** [comment]
Maybe I'm being dense but it seems to me that 00UTC with no offset is 1 hour behind 00UTC +01:00.  Therefore, d = datetime(2000,01,01), which has no offset, should be converted to -1 in the units "hours since 2000-01-01 00:00 +01:00".

BTW - this issue really belongs at https://github.com/Unidata/netcdftime, since we are trying to move netcdftime to a separate package.

**Comment by mdecker** [comment]
I think @pgamez is right. To convert from "2000-01-01 00:00 +01:00" to "2000-01-01 00:00Z" you have to subtract one hour instead of adding it. 
Quoting from https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC: 
> The following times all refer to the same moment: "18:30Z", "22:30+04", "1130−0700", and "15:00−03:30"

**Comment by pgamez** [comment]
Thank you Jeff and Michael... I very appreciate your time

Let me make another test comparing with ncdump. I dumped Jeff's result into a file:

```python
import netCDF4 as nc
from datetime import datetime

units = 'hours since 2000-01-01 00:00 +01:00'
d = datetime(2000, 1, 1)
values = nc.date2num(d, units=units)

with nc.Dataset('test.nc', 'w') as fp:
    fp.createDimension('time', None)
    nctime = fp.createVariable('time', float, ('time',))
    nctime.units = units
    nctime[0] = values
```
Now the result of `ncdump -t`:

```
$ ncdump -t test.nc 
netcdf test {
dimensions:
	time = UNLIMITED ; // (1 currently)
variables:
	double time(time) ;
		time:units = "hours since 2000-01-01 00:00 +01:00" ;

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.8.18" ;
data:

 time = "1999-12-31 23" ;
}
```
ncdump says that local time is 1999-12-31 23, so UTC time must be 1 hour behind, i.e. 1999-12-31 22 and this is not the value of variable `d = datetime(2000, 1, 1)`

Pedro

**Comment by mdecker** [comment]
I took a look at the code and the two places that seem to calculate this wrong for num2date are:
https://github.com/Unidata/netcdf4-python/blob/6b3e0633d72f9cad58360e5c70419e88b86123d0/netCDF4/_netCDF4.pyx#L5286
and the block of code starting at
https://github.com/Unidata/netcdf4-python/blob/6b3e0633d72f9cad58360e5c70419e88b86123d0/netcdftime/_netcdftime.pyx#L855

The respective date2num functions seem to have the same problem, as Pedro suspected. The one in _netCDF4.pyx uses exactly the same faulty timezone logic as above, the one in _netcdftime.pyx fails here:
https://github.com/Unidata/netcdf4-python/blob/6b3e0633d72f9cad58360e5c70419e88b86123d0/netcdftime/_netcdftime.pyx#L801

Example:
```
import netCDF4 as nc
import datetime
units = 'hours since 2000-01-01 00:00+01:00'
dt = datetime.datetime(2000,1,1,1)
print nc.date2num(dt, units)
```
Result: ```0.0```
Expected: ```2.0``` (01:00 UTC is 02:00 UTC+1)

In all cases this can be fixed by inverting the operation when combining the timezone into the result: From local time to UTC the timezone has to be subtracted and from UTC to local time it has to be added.

**Comment by jhamman** [comment]
Any changes to `netcdftime` should be made in the [`netcdftime`](https://github.com/Unidata/netcdftime) repo. Since this conversation has gone on for a while, we'll just leave it here but if a PR is to be made, it should be addressed to `netcdftime`.

**Comment by mdecker** [comment]
pull request at https://github.com/Unidata/netcdftime/pull/16

**Comment by jswhit** [comment]
I've mirrored this pull request here (pull request #689)

**Comment by jswhit** [comment]
pull request #689 merged
