### ISSUE TITLE
CDO grid failure

### ISSUE THREAD

**Issue by sukye** [Unidata/netcdf4-python#692]
I am using netCDF4-python to create netCDF4 files.To create a dimensional 
variable:

createDimension
createVariable

To create other variables:

createVariable(dset.name, dset.dtype, dims)

It works well with panoply or ncdump, but when examined with

cdo sinfo

'Grid coordinates' shows "generic" instead of "lonlat", and unsurprisingly cdo cant subset the dataset:

cdo sellonlatbox (Abort): Unsupported grid type!

Does anyone here know the solution? 
Thanks,-- Jay

**Comment by lesserwhirls** [comment]
Out of curiosity, would you mind sharing a sample file?

**Comment by sukye** [comment]
https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.04/2015/3B-MO.MS.MRG.3IMERG.20150101-S000000-E235959.01.V04A.HDF5

**Comment by lesserwhirls** [comment]
I'm getting a 404 - maybe my URS credentials are not valid to access the dataset?

**Comment by sukye** [comment]
You may need to register at earthdata:
https://urs.earthdata.nasa.gov/users/new

Or I can dump the file info here if you are interested.

**Comment by lesserwhirls** [comment]
Hi @sukye. Looks like I needed to go here first:

https://gpm1.gesdisc.eosdis.nasa.gov/data/GPM_L3/GPM_3IMERGM.04/2015/

and authorize the NASA GESDISC DATA ARCHIVE to my URS account. It's odd that trying to access the link to the data file gave me a 404 rather than redirecting me to this page to request authorization.

Now that I can access the file, I see that groups are being used. According to the last comment on this page (from 4 months ago):

https://code.mpimet.mpg.de/boards/1/topics/192

cdo only supports the netCDF classic model, so groups are not allowed.

**Comment by manuel426** [comment]
Hi, anyone knows how to get a lonlat grid?
