### ISSUE TITLE
Question about default chunksizes

### ISSUE THREAD

**Issue by hans-permana** [Unidata/netcdf4-python#697]
It has been indicated in some parts of the documentation (for example [here](http://www.unidata.ucar.edu/software/netcdf/workshops/2011/nc4chunking/Chunking.html) and [here](http://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_why_it_matters)) that when chunksizes is not specified when calling createVariable(), a default chunksizes is used. However, I could not see that this is the case. I generated a 3-dimensional netcdf file with the following command (from [here](https://github.com/CAB-LAB/cube-performance-test/blob/master/test/cube_utils.py#L39)):
```python
ds.createVariable('value', 'f8', ('time', 'lat', 'lon'), zlib=compression)
```
but I could not find the `_ChunkSizes` attribute in the generated file (with Panoply and HDFView). 

Does default chunksizes simply mean no chunksizes?

**Comment by jswhit** [comment]
from http://www.unidata.ucar.edu/software/netcdf/docs/netcdf_perf_chunking.html

"The current default chunking strategy of the netCDF library is to balance access time along any of a variable's dimensions, by using chunk shapes similar to the shape of the entire variable but small enough that the resulting chunk size is less than or equal to the default chunk size. This differs from an earlier default chunking strategy that always used one for the length of a chunk along any unlimited dimension, and otherwise divided up the number of chunks along fixed dimensions to keep chunk sizes less than or equal to the default chunk size."

Perhaps the _ChunkSizes attribute is only set if you over-ride the default.

**Comment by hans-permana** [comment]
How can I verify if the file is really chunked, regardless of this _ChunkSizes attribute?

**Comment by jswhit** [comment]
using the `chunking` variable method
