### ISSUE TITLE
Inheritance issue

### ISSUE THREAD

**Issue by jreniel** [Unidata/netcdf4-python#788]
Hello,
I have a very large dataset. Normally I would read the variables and then use them to create a custom class. In this case however I cannot do that because it will result in a memory error, and I'm trying to extend the NetCDF4 object with custom functions. In particular I have implemented the following code:

    import netCDF4

    class output(netCDF4.Dataset):
        def __init__(self, *args, **kwargs):
            super(output, self).__init__(*args, **kwargs)
        def my_new_method(self):
            print self.variables

The problem is that after normal program termination I get the following error:

    AttributeError: __getattribute__
    Exception ignored in: 'netCDF4._netCDF4.Dataset.__dealloc__'
    AttributeError: __getattribute__

While everything in the program runs correctly, I would like to avoid this error. What would be the correct way of doing inheritance so that I can avoid this error?

-Jaime

**Comment by jswhit** [comment]
Sorry, I've got nothing.

**Comment by shoyer** [comment]
I would recommend using *composition* instead of inheritance, e.g.,
```
class output(object):
    def __init__(self, *args, **kwargs):
        self.ds = netCDF4.Dataset(*args, **kwargs)
    def my_new_method(self):
        print self.ds.variables
```

`netCDF4.Dataset` really isn't designed for inheritance.

You might also try a library like xarray or Iris that already handles reading data from netCDF files that doesn't fit in memory.

**Comment by jreniel** [comment]
Thanks. That's what I end up doing, I just wasn't sure if it was correct. Thanks for the info!

**Comment by barronh** [comment]
This has bothered me for some time, and because I love netcdf4 so much, I couldn't let it go. Now, I think I have a solution.

# Reproduce the problem:
```
from netCDF4 import Dataset

class reader(Dataset):
    pass

f = reader('temp.nc')
```

Raises
```
AttributeError: __getattribute__
Exception ignored in: 'netCDF4._netCDF4.Dataset.__dealloc__'
AttributeError: __getattribute__
```

Fix the problem:
===========
```
from netCDF4 import Dataset

class reader(Dataset):
    def __del__(self):
        self.close()

f = reader('temp.nc')
```

Does not raise error.

Explanation
========

The `__dealloc__` deconstructor in _netCDF.c checks if `_isopen` call `_close`. Oddly, the `_close` part of the C code has a call to get a string attribute that is not in the direct `_close` code. If you close it before `__dealloc__`, then `_isopen` is `False` and this section of the C code is skipped. 

Because the new `__del__` interface calls `close` there should be no difference in functionality.

It is not clear to me how fix the C code generation.

**Comment by shoyer** [comment]
@barronh this may work for now, but I would still hesitate to rely on it. The behavior of netCDF4.Dataset subclasses is basically undefined. There is no public API or tests for it.

**Comment by barronh** [comment]
@shoyer not quite sure what you mean. There are tests and there are lots of public methods. As long as I rely only upon the public methods (some stable since inception e.g., createVariable) or subclass methods, why would that be problematic? It would seem to have similar risk as composition. A method could change...

Thanks!

**Comment by jswhit** [comment]
@barronh, I can't seem to reproduce this problem with `__dealloc__`. For example, this test program

```python
from netCDF4 import Dataset
import numpy as np

class reader(Dataset):
    pass

f = reader('temp.nc','w')
x = f.createDimension('x',None)
f.description = 'test dataset for inheritance'
v = f.createVariable('v',np.float,'x')
v.long_name = 'foo'
v.units = 'fathoms'
v[0:10] = np.arange(10)
f.close()

f = reader('temp.nc')
print f
f.close()
```

works as expected for me.

I wonder if it's a bug that was fixed in cython, or an issue specific to your netcdf file?

**Comment by shoyer** [comment]
The problem is that some public methods in netCDF4.Dataset may rely upon *other* public methods working exactly like they do in netCDF4.Dataset. If you change the behavior of any of them, others may break in unexpected ways.

This is a classic software design question. If you search for "composition over inheritance" you'll find lots of articles.

**Comment by jswhit** [comment]
I agree with @shoyer that it would be good to add some tests for subclassing.  If either of you has any example use cases that could be distilled into tests that would be a good starting point.

**Comment by jreniel** [comment]
Thanks for the follow ups. I am learning a lot from your interactions.

**Comment by barronh** [comment]
Many of my examples involve managing meta data. I should point out that xarray already offers solutions to many of the problems that I would solve with subclassing.  Even so, I often find that I am faced with meta-data that xarray does not handle (non-CF, e.g, IOAPI). In those cases, I often add functionality by inheritance.

I have complex examples in PseudoNetCDF. PseudoNetCDF.cmaqfiles.ioapi, for example, leverages netCDF4.Dataset and knowledge of the ioapi meta-data to handle map projections, plotting, and automatic updating of IOAPOI meta-data (e.g., updating VAR-LIST after variable subseting or updating VGLVLS after layer interpolation). These are likely too complex for a testcase, but quite useful for me.

A super simple case would be a meta-data updating file. It's an overly simplistic example, but its a start.

```
from netCDF4 import Dataset


class history(Dataset):
    def __init__(self, filename, mode='r', **kwds):
        retv = Dataset.__init__(self, filename, mode=mode, **kwds)
        if mode[:1] in ('w', 'a') or mode[:2] == 'r+':
            from datetime import datetime
            history = getattr(self, 'HISTORY', '')
            if history != '':
                history += '; '
            now = datetime.now().strftime('%Y-%m-%d %H:%M:%S%z')
            history += 'Opened for {} at {}'.format(now, mode)
            self.HISTORY = history

        return retv
```
