### ISSUE TITLE
curl dependency not handled in conda package

### ISSUE THREAD

**Issue by brianmapes** [Unidata/netcdf4-python#803]
I just updated my environment 
conda env update -f MPO624_conda_environment.yml
using an environment that was based on the unidata-python-workshop environment (with netcdf4 in it but not curl explicitly) 

Then, in a code that worked earlier, I got this error upon importing netCDF4: 
"_netCDF4.cpython-36m-darwin.so requires version 10.0.0 or later, but libcurl.4.dylib provides version 9.0.0" 

I was able to fix it by conda update curl, but perhaps the dependency tree needs a quick fix.

**Comment by dopplershift** [comment]
I assume you've installed things from conda-forge. Your problem is odd because while the netcdf4 package (netcdf4-python) doesn't list curl as a dependency, libnetcdf (the netcdf-c library) does list it.

Either way, we here don't control those packages, so best to report on the conda-forge [feedstock](https://github.com/conda-forge/netcdf4-feedstock/issues).
