### ISSUE TITLE
NetCDF: file not found #826 old issue

### ISSUE THREAD

**Issue by DanielIAvila** [Unidata/netcdf4-python#829]
Same problem after installing gdal. But know I have lost all the data. What can I do?

**Comment by jswhit** [comment]
I don't know - seems like there are problems with your set up that go far beyond what we can diagnose here.

**Comment by dopplershift** [comment]
How did you install GDAL? Using Anaconda?

**Comment by DanielIAvila** [comment]
Ok, so here is how I solve my problem. My instructions are clearer than your multiple blogs.

1. If you have Windows 10 or any other running in x64bits and Python 3.x. Download from here the file .whl that better suits you. https://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml for gdal. (if possible try to copy it to the folder where Anaconda is installed).

2. Run as admin Anaconda Prompt and write: `pip install path_where_you_have_downloaded_the_file_before file_name_with_extension_.whl` 

3. GDAL will only work if you install it like this. If you encounter a problem where it says NETCDF file not found. The problem is that the server from which you downloading the information is momentary down. Keep on trying, it will work.

**Comment by dopplershift** [comment]
So, installing GDAL from the wheel file into Anaconda is a **really** bad idea. Is there some reason you can't do:

```
conda install gdal
```
?

**Comment by scw** [comment]
@DanielIAvila you can find what versions of GDAL are available with `conda search gdal`, or by visiting https://anaconda.org and searching directly there. Both the `defaults` channel and `conda-forge` have GDAL packages that work on Windows, and should be available. If you have issues, you can report them to the conda repository. Mixing and matching packages that are from Wheels with binary dependencies (like GDAL and NumPy) will certainly cause problems -- either just use virtualenv and pip, or use conda for everything if at all possible. I don't think this issue is actionable for the netCDF4 library.

**Comment by jswhit** [comment]
closing now
