### ISSUE TITLE
Issue reading large Exodus file on Windows 10

### ISSUE THREAD

**Issue by thucnguyen2908** [Unidata/netcdf4-python#875]
Hi,

I have a Sandia's Exodus mesh as below link (it's larger than 10MB so I cannot attach it here):
https://drive.google.com/file/d/12e8IQaW_iPVUnzPPqrAwEC-dsNho_32L/view?usp=sharing

I try to read it using netCDF4-python (version 1.4.2) on Windows 10 with below Python script:

```
import netCDF4
mesh_data = netCDF4.Dataset("Mesh.exo")
```

but it has never finished (it run over 1 hour then I had to stop it).

On the other hand, I try that on Ubuntu and it works fine there (done after about 10 seconds). 

Hence, I guess there is a Windows specific issue. Could you please help me to debug what is the issue on Windows and fix it if possible? Thanks very much!

Best regards,
Thuc Nguyen

**Comment by jswhit** [comment]
I don't have access to a windows install, so unfortunately I can't help.

**Comment by cgohlke** [comment]
I can reproduce this issue. Apparently it is fixed by upgrading from `netcdf-c-4.4.1.1` to `netcdf-c-4.6.3`. You can find new binaries at <https://www.lfd.uci.edu/~gohlke/pythonlibs/#netcdf4>. Unfortunately `netcdf-c-4.6.3` no longer compiles with VS2008, so this issue is not fixed in the Python 2.7 binaries.

**Comment by jswhit** [comment]
Closing now
