### ISSUE TITLE
floar32 variable, but got int32

### ISSUE THREAD

**Issue by zuec** [Unidata/netcdf4-python#977]
python3.7
netCDF4 1.5.2
numpy 1.17.2

```
    ncInput = Dataset('zmax_layer01.nc')
    lon_Ori = ncInput.variables['Longitude'][:]
    lat_Ori = ncInput.variables['Latitude'][:]
    varDataName = 'MaximumTsunamiElevation'
    varData_Obj = ncInput.variables[varDataName]
    print(varData_Obj,varData_Obj.datatype,varData_Obj.dtype)
    varData_Ori = varData_Obj[:]
    print(varDataName, type(varData_Ori), varData_Ori.shape, varData_Ori.dtype)
```

result:

> <class 'netCDF4._netCDF4.Variable'>
> float32 MaximumTsunamiElevation(Latitude, Longitude)
>     long_name: MaximumTsunamiElevation
>     units: meter
>     scale_factor: 1
>     add_offset: 0
> unlimited dimensions: 
> current shape = (1020, 1725)
> filling on, default _FillValue of 9.969209968386869e+36 used float32 float32
> MaximumTsunamiElevation <class 'numpy.ma.core.MaskedArray'> (1020, 1725) int32
> 

The MaximumTsunamiElevation variable in my file is a float32 type, but the int32 is read out by netCDF4.Dataset. I don't know why, I can't debug the c code of netcdf. Who can help me, thank you very much

**Comment by zuec** [comment]
After reading this code site-packages\xarray\tests\test_backends.py.
I found out that I need to execute ncInput.set_auto_maskandscale(False) and then read it correctly.

**Comment by jswhit** [comment]
For future reference, the reason this is happening is because the `scale_factor` and `add_offset` attributes are integers.  Following the conventions described [here](https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html), the data array is cast to the type of the `scale_factor` and `add_offset` attributes. Quoting from the link above

"When scale_factor and add_offset are used for packing, the associated variable (containing the packed data) is typically of type byte or short, whereas the unpacked values are intended to be of type float or double. The attributes scale_factor and add_offset should both be of the type intended for the unpacked data, e.g. float or double."
